openapi: 3.1.0
info:
  title: LLD Research API
  version: 1.0.0
servers:
  - url: https://api.smlx.online
paths:
  /run/:
    post:
      operationId: runExperiment
      description: Run a diffusion model experiment.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                model:
                  type: string
                  enum: [dream7b, llada]
                steps:
                  type: integer
      responses:
        "200":
          description: Experiment result
  /log/list:
    get:
      operationId: listLogs
      description: List all previous experiment logs.
      responses:
        "200":
          description: List of logs
  /visualize/:
    get:
      operationId: visualizeEntropy
      description: Visualize the entropy curve from a log.
      parameters:
        - name: filename
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Base64-encoded entropy image

  /summarize/:
    get:
      operationId: summarizeLog
      description: Summarize the experiment log file
      parameters:
        - name: filename
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Text summary of the experiment

  /compare/:
    get:
      operationId: compareEntropy
      description: Compare entropy trends from multiple experiment logs
      parameters:
        - name: filenames
          in: query
          required: true
          explode: true
          style: form
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: Base64-encoded entropy comparison image

